#! /bin/bash

# The MIT License (MIT)
# Copyright (c) 2024 Emeer Adhamian (github.com/kode-trek)
# https://raw.githubusercontent.com/kode-trek/mede/main/LICENSE

RED='\033[1;35m'
GREEN='\033[1;36m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
NC='\033[0m' #No-Color

printf "${GREEN}[MEDia Editor]${NC} "
printf "basic tools to edit image/audio/video files.""\n""\n"

ping -c 2 github.com 1>/dev/null 2>/dev/null
e=$?
if [[ $e != 0 ]]
then
 printf "${YELLOW}[WARNING]${NC} internet connection not found.""\n"
 read -p "CONTINUE? (Y/N): " confirm && [[ $confirm == [yY] ]] || exit 1
 echo
fi

if [[ "$1" == "--roll-back" ]]
then
 trap "exit" INT

 printf "${BLUE}[]${NC} package(s)/file(s) to be removed:${NC}""\n""\n"
 printf " * ffmpeg""\n"
 printf " * imagemagick""\n"
 printf " * recordmydesktop""\n"
 printf " * timidity""\n"
 printf "\n"
 printf " * /usr/bin/mede-bin/""\n"
 printf " * /usr/lib/mede/""\n"
 printf " * /usr/bin/mede""\n"
 printf "\n"
 read -p "CONTINUE? (Y/N): " confirm && [[ $confirm == [yY] ]] || exit 1
 echo

 sudo apt-get remove ffmpeg -y
 sudo apt-get remove imagemagick -y
 sudo apt-get remove recordmydesktop -y
 sudo apt-get remove timidity -y
 sudo apt-get install -f -y
 sudo apt-get update --fix-missing -y

 sudo rm -rf /usr/bin/mede-bin/
 sudo rm -rf /usr/lib/mede/
 sudo rm -rf /usr/bin/mede

 sudo rm -rf /etc/ImageMagick-*/policy.xml

 printf "${BLUE}[OK]${NC} successfully un-installed.""\n"
 read -n1 -r -p "press ANY-KEY to EXIT..." key
 exit
fi

lab51cc 1>/dev/null 2>/dev/null
e=$?
if [[ $e != 0 ]]
then
 printf "${YELLOW}[REQUIREMENT]${NC} lab51cc""\n"
 printf "${YELLOW}[DEVELOPMENT]${NC} github.com/kode-trek/lab51""\n"
 read -n1 -r -p "press ANY-KEY to EXIT..." key
 exit
fi

printf "${BLUE}[]${NC} package(s)/file(s) to be installed:${NC}""\n""\n"
printf " * ffmpeg""\n"
printf " * imagemagick""\n"
printf " * recordmydesktop""\n"
printf " * timidity""\n"
printf "\n"
printf " * /usr/lib/mede/""\n"
printf " * /usr/bin/mede-bin/""\n"
printf " * /usr/bin/mede""\n"
printf "\n"

flg=0
if [[ -e /usr/lib/mede ]]
then
 flg=1
fi
if [[ -e /usr/bin/mede-bin/ ]]
then
 flg=1
fi
if [[ -e /usr/bin/mede ]]
then
 flg=1
fi
if [[ $flg == 1 ]]
then
 read -p "RE-INSTALL? (Y/N): " confirm && [[ $confirm == [yY] ]] || exit 1
else
 read -p "CONTINUE? (Y/N): " confirm && [[ $confirm == [yY] ]] || exit 1
fi

echo
trap "exit" INT

#sudo apt-get install -f -y
#sudo apt update --fix-missing -y
#sudo apt-get install ffmpeg -y
#sudo apt-get install imagemagick -y
#sudo apt-get install recordmydesktop -y
if [[ "$1" == "--all" ]]
then
 sudo apt-get install timidity -y
fi

echo
cd lib

sudo rm -rf /etc/ImageMagick-*/policy.xml
sudo cp 0-asset/policy-1.xml /etc/ImageMagick-6/policy.xml
sudo chmod 644 /etc/ImageMagick-6/policy.xml

sudo rm -rf /usr/bin/mede-bin/
sudo rm -rf /usr/lib/mede/

sudo mkdir /usr/bin/mede-bin/
sudo mkdir /usr/lib/mede/

sudo cp -r 0-asset/mede-asset/ /usr/lib/mede
sudo chmod 775 /usr/lib/mede/mede-asset

chmod 755 mede
sudo cp mede /usr/bin/

lab51cc help.cc
sudo mv help_* /usr/bin/mede-bin/help
echo ""

lab51cc intro.cc
sudo mv intro_* /usr/bin/mede-bin/intro
echo ""

lab51cc menu.cc
sudo mv menu_* /usr/bin/mede-bin/menu
echo ""

cd 0-asset
lab51cc main_sample.cc
sudo mv main_sample_* /usr/bin/mede-bin/sample
echo ""
cd ..

cd cen
lab51cc main_cen.cc
sudo mv main_cen_* /usr/bin/mede-bin/cen
echo ""
cd ..

cd crop
lab51cc main_crop.cc
sudo mv main_crop_* /usr/bin/mede-bin/crop
echo ""
cd ..

cd laud
lab51cc main_laud.cc
sudo mv main_laud_* /usr/bin/mede-bin/laud
echo ""
cd ..

cd merge
lab51cc main_merge.cc
sudo mv main_merge_* /usr/bin/mede-bin/merge
echo ""
cd ..

cd meta
lab51cc main_meta.cc
sudo mv main_meta_* /usr/bin/mede-bin/meta
echo ""
cd ..

cd pub
lab51cc main_pub.cc
sudo mv main_pub_* /usr/bin/mede-bin/pub
echo ""
cd ..

cd rot
lab51cc main_rot.cc
sudo mv main_rot_* /usr/bin/mede-bin/rot
echo ""
cd ..

cd snap
lab51cc main_snap.cc
sudo mv main_snap_* /usr/bin/mede-bin/snap
echo ""
cd ..

cd sub
lab51cc main_sub.cc
sudo mv main_sub_* /usr/bin/mede-bin/sub
echo ""
cd ..

cd trim
lab51cc main_trim.cc
sudo mv main_trim_* /usr/bin/mede-bin/trim
echo ""

cd ../..

printf "${BLUE}[OK]${NC} successfully installed.""\n"
read -n1 -r -p "press ANY-KEY to EXIT..." key
